import { ActivityKeyIDEnum } from "@carbon/enum/activity.enum";

export const ACTIVITY_CONFIG_VIEW_PAGE_CONSTANT = [
    ActivityKeyIDEnum.PROCESS_EMISSION,
    ActivityKeyIDEnum.CHP_ATTRIBUTION,
    ActivityKeyIDEnum.PROCESS_ELECTRICITY_CONSUMPTION,
    ActivityKeyIDEnum.PROCESS_HEAT_CONSUMPTION,
    ActivityKeyIDEnum.PROCESS_FUEL_CONSUMPTION,
    ActivityKeyIDEnum.PURCHASED_PRECURSOR,
    ActivityKeyIDEnum.PROCESS_PRECURSOR_CONSUMPTION,
    ActivityKeyIDEnum.PROCESS_ELECTRICITY_EXPORT,
    ActivityKeyIDEnum.PROCESS_HEAT_EXPORT,
    ActivityKeyIDEnum.PROCESS_PRECURSOR_EXPORT,
    ActivityKeyIDEnum.PROCESS_WASTE_GAS_EXPORT,
    ActivityKeyIDEnum.PROCESS_INTERMEDIATE_PRODUCT_EXPORT,
    ActivityKeyIDEnum.PROCESS_PRODUCTION_LEVEL,
    ActivityKeyIDEnum.CARBON_PRICING
];
