export enum EmissionDataTypeEnum {
    ACTIVITY_DATA = 'ACTIVITY_DATA',
    SUBSIDIARY_EMISSION = 'SUBSIDIARY_EMISSION',
    MERGER_ACQUISITION = 'MERGER_ACQUISITION',
    DIVESTMENT = 'DIVESTMENT',
    OUTSOURCING = 'OUTSOURCING',
    INSOURCING = 'INSOURCING'
}